version: '3.7'

services:

  frontend:
    container_name: elite-barefoot-frontend
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    stdin_open: true
