const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILED = 'LOGOUT_FAILED'

const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'
export const USER_PROFILE = 'USER_PROFILE'
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED'
export const USER_PROFILE_DATA = 'USER_PROFILE_DATA'
export { LOGOUT_FAILED, LOGOUT_SUCCESS, LOGIN_SUCCESS }
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAIL = 'FETCH_REVIEWS_FAIL';
export const SAVE_REVIEWS_SUCCESS = 'SAVE_REVIEWS_SUCCESS';
export const SAVE_REVIEWS_FAIL = 'SAVE_REVIEWS_FAIL';
export const FETCH_RATING_SUCCESS = 'FETCH_RATING_SUCCESS';
export const FETCH_RATING_FAIL = 'FETCH_RATING_FAIL';
export const SAVE_RATING_SUCCESS = 'SAVE_RATING_SUCCESS';
export const SAVE_RATING_FAIL = 'SAVE_RATING_FAIL';