const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILED = 'LOGOUT_FAILED'

const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'
export const USER_PROFILE = 'USER_PROFILE'
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED'
export const USER_PROFILE_DATA = 'USER_PROFILE_DATA'
export { LOGOUT_FAILED, LOGOUT_SUCCESS, LOGIN_SUCCESS }
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const GET_PERMISSIONS_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_PERMISSIONS_FAIL = "GET_ROLES_FAIL";
