const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILED = 'LOGOUT_FAILED'

const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'
export const USER_PROFILE = 'USER_PROFILE'
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED'
export const USER_PROFILE_DATA = 'USER_PROFILE_DATA'
export { LOGOUT_FAILED, LOGOUT_SUCCESS, LOGIN_SUCCESS }


export const GET_LOCATIONS = 'GET_LOCATIONS';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const GET_ACCOMODATIONS = 'GET_ACCOMODATIONS';
export const DELETE_ACCOMODATION = 'DELETE_ACCOMODATION';
export const CREATE_ACCOMODATION = 'CREATE_ACCOMODATION';
