export const ACCOMODATION_LIST_REQUEST = 'ACCOMODATION_LIST_REQUEST';
export const ACCOMODATION_LIST_SUCCESS = 'ACCOMODATION_LIST_SUCCESS';
export const ACCOMODATION_LIST_FAIL = 'ACCOMODATION_LIST_FAIL';
