export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const FETCH_TRAVEL_START = 'FETCH_TRAVEL_START';
export const FETCH_TRAVEL_SUCCESS = 'FETCH_TRAVEL_SUCCESS';
export const FETCH_TRAVEL_FAIL = 'FETCH_TRAVEL_FAIL';
